services:
  node-app-receiver:
    image: node:24-alpine3.20
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3001"
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - rabbitmq-shared

networks:
  rabbitmq-shared:
    external: true
    name: rabbitmq-fastify-example_default
